config/routes.rb
Rails.application.routes.draw do
  resources :phones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :number, presence: true
  validates :number, unique: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController

  def index
    @phones = Phone.all
  end

  def new
    @phone = Phone.new
  end

  def create
    @phone = Phone.create(phone_params)
    byebug
    if @phone.valid?
      redirect_to phones_path
    else
      render :new
    end
  end

  private

  def phone_params
    params.require(:phone).permit(:number, :manufacturer)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mydbapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phones/index.html.erb
 <h1>Phones</h1>

 <table>
   <tr>
     <th>Number</th>
     <th>Manufacturer</th>
   </tr>
   <% @phones.each do |phone| %>
     <tr>
       <td><%= phone.number %></td>
       <td><%= phone.manufacturer %></td>
     </tr>
   <% end %>
 </table>

 <%= link_to 'Add a new phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>Add a new phone</h1>

<%= form_for @phone do |form| %>
  <%= form.label :number %><br>
  <%= form.text_field :number %><br>
  <%= form.label :manufacturer %><br>
  <%= form.text_field :manufacturer %><br>
  <%= form.submit %>
<% end %>